#!/bin/bash

# args: source

set -e

if [[ "" == "$SCS_REQUIRE_MYSQL" ]]; then
    SCS_REQUIRE_MYSQL=127.0.0.1:3306
fi

sed -i "s/env\[SCS_REQUIRE_MYSQL\] = \(.*\)/env[SCS_REQUIRE_MYSQL] = $SCS_REQUIRE_MYSQL/" /etc/php-fpm/php-fpm.ini

if [ "run" != "$1" ]; then
    supervisorctl -c /etc/supervisor.conf restart php-fpm
fi
